name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"
      - "dev"

  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/${{ github.repository }}-${{ github.ref_name }}/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: pip install -r requirements.txt --cache-dir /opt/hostedtoolcache/${{ github.repository }}-${{ github.ref_name }}/pip

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: vontainment/v-gpt-qdrant-api
          flavor: latest=false
          tags: |
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/dev' }}
            type=sha,priority=100,enable=${{ github.event_name == 'push' }}

      - name: Cache Docker build layers
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/${{ github.repository }}-${{ github.ref_name }}/build
          key: docker-build-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            docker-build-${{ runner.os }}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/opt/hostedtoolcache/${{ github.repository }}-${{ github.ref_name }}/build
          cache-to: type=local,dest=/opt/hostedtoolcache/${{ github.repository }}-${{ github.ref_name }}/build-new,mode=max

      - name: Rotate build cache
        run: |
          rm -rf /opt/hostedtoolcache/${{ github.repository }}-${{ github.ref_name }}/build
          mv /opt/hostedtoolcache/${{ github.repository }}-${{ github.ref_name }}/build-new /opt/hostedtoolcache/${{ github.repository }}-${{ github.ref_name }}/build
